changelog:
  categories:
    - title: Added
      labels:
        - new
    - title: Fixed
      labels:
        - fix
    - title: Changed
      labels:
        - update
    - title: Removed
      labels:
        - remove
