apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    control-plane: controller-manager