apiVersion: v1
kind: ConfigMap
metadata:
  name: nautes-configs
  namespace: system
data:
  componentCategoryDefinition.yaml: |
    host:
      - oauthProxy
      - gateway
      - secretManagement
    worker:
      virtual:
          deployment:
            - multiTenant
            - secretSync
            - deployment
            - progressiveDelivery
            - secretManagement
          pipeline:
            - multiTenant
            - secretSync
            - gateway
            - deployment
            - eventListener
            - pipeline
            - secretManagement
      physical:
          deployment:
            - multiTenant
            - secretSync
            - gateway
            - deployment
            - progressiveDelivery
            - secretManagement
          pipeline:
            - multiTenant
            - secretSync
            - gateway
            - deployment
            - eventListener
            - oauthProxy
            - secretManagement
            - pipeline