apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
          - name: log
            mountPath: "/opt/nautes/log"
      volumes:
      - name: log
        persistentVolumeClaim:
          claimName: log