apiVersion: v1
kind: ConfigMap
metadata:
  name: nautes-configs
  namespace: system
data:
  thirdPartComponents.yaml: |
    - name: tekton
      namespace: tekton-pipelines
      type: pipeline
      default: true
      general: false
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/tekton
      - cluster_templates/runtimes/_RUNTIME_/production/tekton-app.yaml
      - cluster_templates/runtimes/_RUNTIME_/production/tekton-cluster-tasks-app.yaml
    - name: argocd
      namespace: argocd
      type: deployment
      default: true
      general: true
      installPath:
      - cluster_templates//runtimes/_RUNTIME_/argocd
    - name: fluxcd
      namespace: fluxcd
      type: deployment
      default: false
      general: false
      installPath:
      - cluster_templates//runtimes/_RUNTIME_/fluxcd
    - name: argo-events
      namespace: argo-events
      type: eventListener
      default: true
      general: false
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/argo-events-app.yaml
    - name: argo-rollouts
      namespace: argo-rollouts
      type: progressiveDelivery
      default: true
      general: false
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/argo-rollouts-app.yaml
    - name: hnc
      namespace: hnc-system
      type: multiTenant
      default: true
      general: true
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/hnc-app.yaml
    - name: cert-manager
      namespace: cert-manager
      type: certMgt
      default: true
      general: true
      installPath:
      - tenant-repo-template/cert-manager
    - name: vault
      namespace: vault
      type: secretMgt
      default: true
      general: true
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/vault-app.yaml
      - cluster_templates/runtimes/_RUNTIME_/production/vault-resources-app.yaml
    - name: external-secrets
      namespace: external-secrets
      type: secretSync
      default: true
      general: true
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/external-secrets-app.yaml
      - cluster_templates/runtimes/_RUNTIME_/production/external-secrets-resources-app.yaml
    - name: oauth2-proxy
      namespace: oauth2-proxy
      type: oauth2-proxy
      default: true
      general: false
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/oauth2-proxy-app.yaml
      - cluster_templates/runtimes/_RUNTIME_/production/oauth2-proxy-resources-app.yaml
    - name: traefik
      namespace: traefik
      type: ingressController
      default: true
      general: true
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/traefik-app.yaml
      - cluster_templates/runtimes/_RUNTIME_/production/traefik-resources-app.yaml
    - name: nginx-ingress
      namespace: nginx-ingress
      type: ingressController
      default: false
      general: false
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/nginx-ingress-app.yaml
      - cluster_templates/runtimes/_RUNTIME_/production/nginx-ingress-resources-app.yaml
    - name: apisix-ingress
      namespace: apisix-ingress
      type: ingressController
      default: false
      general: false
      installPath:
      - cluster_templates/runtimes/_RUNTIME_/production/apisix-ingress-app.yaml
      - cluster_templates/runtimes/_RUNTIME_/production/apisix-ingress-resources-app.yaml
