---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nautes-resource-nautes-io-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster.kb.io
  rules:
  - apiGroups:
    - nautes.resource.nautes.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - clusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nautes-resource-nautes-io-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster.kb.io
  rules:
  - apiGroups:
    - nautes.resource.nautes.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nautes-resource-nautes-io-v1alpha1-coderepo
  failurePolicy: Fail
  name: vcoderepo.kb.io
  rules:
  - apiGroups:
    - nautes.resource.nautes.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - coderepoes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nautes-resource-nautes-io-v1alpha1-deploymentruntime
  failurePolicy: Fail
  name: vdeploymentruntime.kb.io
  rules:
  - apiGroups:
    - nautes.resource.nautes.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deploymentruntimes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nautes-resource-nautes-io-v1alpha1-environment
  failurePolicy: Fail
  name: venvironment.kb.io
  rules:
  - apiGroups:
    - nautes.resource.nautes.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - environments
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nautes-resource-nautes-io-v1alpha1-productprovider
  failurePolicy: Fail
  name: vproductprovider.kb.io
  rules:
  - apiGroups:
    - nautes.resource.nautes.io
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - productproviders
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nautes-resource-nautes-io-v1alpha1-projectpipelineruntime
  failurePolicy: Fail
  name: vprojectpipelineruntime.kb.io
  rules:
  - apiGroups:
    - nautes.resource.nautes.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - projectpipelineruntimes
  sideEffects: None
