# permissions for end users to edit artifactrepoproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artifactrepoprovider-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoproviders/status
  verbs:
  - get
