# permissions for end users to view artifactrepoproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artifactrepoprovider-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoproviders/status
  verbs:
  - get
