# permissions for end users to view artifactrepoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artifactrepo-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoes/status
  verbs:
  - get
