# permissions for end users to edit artifactrepoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artifactrepo-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - artifactrepoes/status
  verbs:
  - get
