# permissions for end users to edit coderepobindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coderepobinding-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepobindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepobindings/status
  verbs:
  - get
