# permissions for end users to view coderepobindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coderepobinding-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepobindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepobindings/status
  verbs:
  - get
