# permissions for end users to edit coderepoproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coderepoprovider-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoproviders/status
  verbs:
  - get
