# permissions for end users to view coderepoproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coderepoprovider-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoproviders/status
  verbs:
  - get
