# permissions for end users to view coderepoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coderepo-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - coderepoes/status
  verbs:
  - get
