# permissions for end users to edit deploymentruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentruntime-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - deploymentruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - deploymentruntimes/status
  verbs:
  - get
