# permissions for end users to view deploymentruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentruntime-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - deploymentruntimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - deploymentruntimes/status
  verbs:
  - get
