# permissions for end users to view productproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: productprovider-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - productproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - productproviders/status
  verbs:
  - get
