# permissions for end users to view products.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: product-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - products
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - products/status
  verbs:
  - get
