# permissions for end users to edit productproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: productprovider-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - productproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - productproviders/status
  verbs:
  - get
