# permissions for end users to edit projectartifactrepoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectartifactrepo-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - projectartifactrepoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - projectartifactrepoes/status
  verbs:
  - get
