# permissions for end users to view projectartifactrepoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectartifactrepo-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - projectartifactrepoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - projectartifactrepoes/status
  verbs:
  - get
