# permissions for end users to view projectpipelineruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectpipelineruntime-viewer-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - projectpipelineruntimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - projectpipelineruntimes/status
  verbs:
  - get
