# permissions for end users to edit projectpipelineruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectpipelineruntime-editor-role
rules:
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - projectpipelineruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nautes.resource.nautes.io
  resources:
  - projectpipelineruntimes/status
  verbs:
  - get
