// Copyright 2023 Nautes Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: deploymentruntime/v1/deploymentruntime.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Deploymentruntime_GetDeploymentRuntime_FullMethodName    = "/api.deploymentruntime.v1.Deploymentruntime/GetDeploymentRuntime"
	Deploymentruntime_ListDeploymentRuntimes_FullMethodName  = "/api.deploymentruntime.v1.Deploymentruntime/ListDeploymentRuntimes"
	Deploymentruntime_SaveDeploymentRuntime_FullMethodName   = "/api.deploymentruntime.v1.Deploymentruntime/SaveDeploymentRuntime"
	Deploymentruntime_DeleteDeploymentRuntime_FullMethodName = "/api.deploymentruntime.v1.Deploymentruntime/DeleteDeploymentRuntime"
)

// DeploymentruntimeClient is the client API for Deploymentruntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploymentruntimeClient interface {
	GetDeploymentRuntime(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	ListDeploymentRuntimes(ctx context.Context, in *ListsRequest, opts ...grpc.CallOption) (*ListsReply, error)
	SaveDeploymentRuntime(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error)
	DeleteDeploymentRuntime(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
}

type deploymentruntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploymentruntimeClient(cc grpc.ClientConnInterface) DeploymentruntimeClient {
	return &deploymentruntimeClient{cc}
}

func (c *deploymentruntimeClient) GetDeploymentRuntime(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, Deploymentruntime_GetDeploymentRuntime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentruntimeClient) ListDeploymentRuntimes(ctx context.Context, in *ListsRequest, opts ...grpc.CallOption) (*ListsReply, error) {
	out := new(ListsReply)
	err := c.cc.Invoke(ctx, Deploymentruntime_ListDeploymentRuntimes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentruntimeClient) SaveDeploymentRuntime(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Deploymentruntime_SaveDeploymentRuntime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deploymentruntimeClient) DeleteDeploymentRuntime(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, Deploymentruntime_DeleteDeploymentRuntime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploymentruntimeServer is the server API for Deploymentruntime service.
// All implementations must embed UnimplementedDeploymentruntimeServer
// for forward compatibility
type DeploymentruntimeServer interface {
	GetDeploymentRuntime(context.Context, *GetRequest) (*GetReply, error)
	ListDeploymentRuntimes(context.Context, *ListsRequest) (*ListsReply, error)
	SaveDeploymentRuntime(context.Context, *SaveRequest) (*SaveReply, error)
	DeleteDeploymentRuntime(context.Context, *DeleteRequest) (*DeleteReply, error)
	mustEmbedUnimplementedDeploymentruntimeServer()
}

// UnimplementedDeploymentruntimeServer must be embedded to have forward compatible implementations.
type UnimplementedDeploymentruntimeServer struct {
}

func (UnimplementedDeploymentruntimeServer) GetDeploymentRuntime(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentRuntime not implemented")
}
func (UnimplementedDeploymentruntimeServer) ListDeploymentRuntimes(context.Context, *ListsRequest) (*ListsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeploymentRuntimes not implemented")
}
func (UnimplementedDeploymentruntimeServer) SaveDeploymentRuntime(context.Context, *SaveRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDeploymentRuntime not implemented")
}
func (UnimplementedDeploymentruntimeServer) DeleteDeploymentRuntime(context.Context, *DeleteRequest) (*DeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeploymentRuntime not implemented")
}
func (UnimplementedDeploymentruntimeServer) mustEmbedUnimplementedDeploymentruntimeServer() {}

// UnsafeDeploymentruntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploymentruntimeServer will
// result in compilation errors.
type UnsafeDeploymentruntimeServer interface {
	mustEmbedUnimplementedDeploymentruntimeServer()
}

func RegisterDeploymentruntimeServer(s grpc.ServiceRegistrar, srv DeploymentruntimeServer) {
	s.RegisterService(&Deploymentruntime_ServiceDesc, srv)
}

func _Deploymentruntime_GetDeploymentRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentruntimeServer).GetDeploymentRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploymentruntime_GetDeploymentRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentruntimeServer).GetDeploymentRuntime(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploymentruntime_ListDeploymentRuntimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentruntimeServer).ListDeploymentRuntimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploymentruntime_ListDeploymentRuntimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentruntimeServer).ListDeploymentRuntimes(ctx, req.(*ListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploymentruntime_SaveDeploymentRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentruntimeServer).SaveDeploymentRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploymentruntime_SaveDeploymentRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentruntimeServer).SaveDeploymentRuntime(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploymentruntime_DeleteDeploymentRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploymentruntimeServer).DeleteDeploymentRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploymentruntime_DeleteDeploymentRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploymentruntimeServer).DeleteDeploymentRuntime(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Deploymentruntime_ServiceDesc is the grpc.ServiceDesc for Deploymentruntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deploymentruntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.deploymentruntime.v1.Deploymentruntime",
	HandlerType: (*DeploymentruntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeploymentRuntime",
			Handler:    _Deploymentruntime_GetDeploymentRuntime_Handler,
		},
		{
			MethodName: "ListDeploymentRuntimes",
			Handler:    _Deploymentruntime_ListDeploymentRuntimes_Handler,
		},
		{
			MethodName: "SaveDeploymentRuntime",
			Handler:    _Deploymentruntime_SaveDeploymentRuntime_Handler,
		},
		{
			MethodName: "DeleteDeploymentRuntime",
			Handler:    _Deploymentruntime_DeleteDeploymentRuntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deploymentruntime/v1/deploymentruntime.proto",
}
