# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: runtime-controller-

# Labels to add to all resources and selectors.
commonLabels:
  control-plane: runtime-operator

resources:
- ../../base

patchesStrategicMerge:
- manager_patch.yaml
- trigger_templates.yaml
