apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        command:
        - "bin/runtime-operator"
        volumeMounts:
        - name: plugins
          mountPath: /opt/nautes/plugins
      volumes:
      - name: plugins
        persistentVolumeClaim:
          claimName: plugins
