// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsAuthFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_AUTH_FAILED.String() && e.Code == 401
}

func ErrorAuthFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_AUTH_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsActionNotAllow(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ACTION_NOT_ALLOW.String() && e.Code == 403
}

func ErrorActionNotAllow(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_ACTION_NOT_ALLOW.String(), fmt.Sprintf(format, args...))
}

func IsResourceNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RESOURCE_NOT_FOUND.String() && e.Code == 404
}

func ErrorResourceNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_RESOURCE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsInputArgError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INPUT_ARG_ERROR.String() && e.Code == 400
}

func ErrorInputArgError(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INPUT_ARG_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsInternalServiceError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INTERNAL_SERVICE_ERROR.String() && e.Code == 500
}

func ErrorInternalServiceError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INTERNAL_SERVICE_ERROR.String(), fmt.Sprintf(format, args...))
}
